services:
  postgresql:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=${POSTGRES_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRESQL_DATABASE=${POSTGRES_DATABASE}
    ports:
        - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
        - db:/bitnami/postgresql
    networks:
      - gerenciador-partidas
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - gerenciador-partidas

networks:
  gerenciador-partidas:
    driver: bridge

volumes:
    db: