services:
  postgresql:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=natherzito
      - POSTGRESQL_PASSWORD=minhasenhasupertop
      - POSTGRESQL_DATABASE=gerenciador_partidas
    ports:
        - "5432:5432"
    volumes:
        - db:/bitnami/postgresql
    networks:
      - gerenciador-partidas

networks:
  gerenciador-partidas:
    driver: bridge

volumes:
    db: